### ISSUE TITLE
Spam prevention

### ISSUE THREAD

**Issue by jamescoxon** [NanoSMS/nano_sms_server#19]
As SMS replies have a fee we need to be careful to avoid being spammed, add a limiter with cooling off period to avoid this.

**Comment by TertiusN** [comment]
Added a 15 second rate limit to user requests:
  
```
  if (user_details.datetime.now() - user_details.time).total_seconds() < 15:
        time.sleep(15)
        print(user_details.phonenumber + ' user rate locked for 15 seconds')
```

**Comment by jamescoxon** [comment]
Just loaded up master and am getting this:
`  File "/root/nano_sms_server/run.py", line 401, in sms_ahoy_reply
    if (user_details.datetime.now() - user_details.time).total_seconds() < 15:
AttributeError: 'User' object has no attribute 'datetime'
`
